---
is_debug: true
listen:
  type: port
  bind_ip: 127.0.0.1
  port: 8080
mongodb:
    host: localhost
    port: 27017
    database: go_mongo
    auth_db:
    collection: users
    username:
    password:
postgres:
    host: localhost
    port: 5432
    database: testdb
    username: postgres
    password: root

