services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=go_rest_api
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
        - '5438:5432'
volumes:
  postgres-data:
